{
  description = "Plant App — Kotlin Multiplatform with Compose for Android & iOS";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    android-nixpkgs = {
      url = "github:tadfisher/android-nixpkgs/stable";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    devshell = {
      url = "github:numtide/devshell";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    opencode.url = "github:anomalyco/opencode/v1.14.40";
  };

  outputs = { self, nixpkgs, android-nixpkgs, devshell, opencode }:
    let
      # Change to "aarch64-linux" if on ARM — also update the system image below
      system = "x86_64-linux";

      pkgs = import nixpkgs {
        inherit system;
        overlays = [ devshell.overlays.default ];
      };

      # ── Android SDK ────────────────────────────────────────────────────
      # Adjust packages here when bumping API levels.
      # List all available packages with:
      #   nix flake show github:tadfisher/android-nixpkgs/stable
      sdkPath = "${android-sdk}/share/android-sdk";

      android-sdk = android-nixpkgs.sdk.${system} (sdkPkgs: with sdkPkgs; [
        cmdline-tools-latest
        build-tools-36-0-0
        platform-tools
        platforms-android-35
        platforms-android-36
        emulator
        sources-android-35
        # For aarch64-linux, replace with:
        #   system-images-android-35-google-apis-arm64-v8a
        system-images-android-35-google-apis-x86-64
      ]);

      # ── Emulator runtime libraries ─────────────────────────────────────
      # The Android emulator ships pre-built binaries that need these on
      # NixOS.  Add more here if you hit "cannot open shared object" errors.
      emulatorLibs = with pkgs; [
        # Graphics / display
        libGL
        vulkan-loader
        libx11
        libxext
        libxrandr
        libxcb
        libxi
        libxcursor
        libxfixes
        # Audio
        libpulseaudio
        alsa-lib
        # Misc runtime deps
        nss
        nspr
        fontconfig
        freetype
        stdenv.cc.cc.lib
        expat
        libdrm
        dbus
        systemd
      ];

    in {
      devShells.${system}.default = pkgs.devshell.mkShell {
        name = "plant-app-dev";

        motd = ''
          🌱 {bold}{green}Plant App{reset} — Development Environment
          {italic}Run 'menu' to see available commands{reset}
        '';

        devshell.startup.setup-sdk.text = ''
          mkdir -p "$ANDROID_AVD_HOME"
          echo "## Auto-generated by nix devshell — do not edit manually" > local.properties
          echo "sdk.dir=$ANDROID_HOME" >> local.properties
        '';

        env = [
          { name = "ANDROID_HOME";     value = sdkPath; }
          { name = "ANDROID_SDK_ROOT"; value = sdkPath; }
          { name = "ANDROID_AVD_HOME"; eval = "$PRJ_ROOT/.android/avd"; }
          { name = "JAVA_HOME";        value = "${pkgs.jdk17}"; }
          {
            # Tell AGP to use the Nix-patched aapt2 instead of downloading
            # an unpatched binary from Maven (which won't run on NixOS).
            name  = "GRADLE_OPTS";
            value = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${sdkPath}/build-tools/36.0.0/aapt2";
          }
          {
            # Emulator GPU / audio libraries
            name  = "LD_LIBRARY_PATH";
            value = pkgs.lib.makeLibraryPath emulatorLibs;
          }
        ];

        packages = [
          pkgs.jdk17
          android-sdk
          pkgs.kotlin-language-server
          opencode.packages.${system}.opencode
        ];

        commands = [

          # ── Build ────────────────────────────────────────────────────
          {
            category = "build";
            name     = "build-debug";
            help     = "Build the Android debug APK";
            command  = "./gradlew :androidApp:assembleDebug";
          }
          {
            category = "build";
            name     = "build-release";
            help     = "Build the Android release APK";
            command  = "./gradlew :androidApp:assembleRelease";
          }

          # ── Android / Emulator ───────────────────────────────────────
          {
            category = "android";
            name     = "create-avd";
            help     = "Create an Android Virtual Device (Pixel 6, API 35)";
            command  = ''
              avdmanager create avd \
                --name "plant-app-test" \
                --package "system-images;android-35;google_apis;x86_64" \
                --device "pixel_6" \
                --force
              echo ""
              echo "✅ AVD 'plant-app-test' created.  Run 'start-emulator' to launch it."
            '';
          }
          {
            category = "android";
            name     = "list-avds";
            help     = "List available Android Virtual Devices";
            command  = "avdmanager list avd";
          }
          {
            category = "android";
            name     = "start-emulator";
            help     = "Start the emulator (pass extra flags after --)";
            command  = ''
              emulator -avd plant-app-test -gpu auto "$@" &
              echo "⏳ Emulator starting in background..."
              echo "   Run 'adb wait-for-device && list-devices' to verify."
            '';
          }
          {
            category = "android";
            name     = "run-app";
            help     = "Build, install and launch the app on device/emulator";
            command  = ''
              echo "🔨 Building and installing..."
              ./gradlew :androidApp:installDebug && \
              adb shell am start -n org.michael.plantapp/.MainActivity && \
              echo "✅ App launched!"
            '';
          }
          {
            category = "android";
            name     = "list-devices";
            help     = "List connected devices and running emulators";
            command  = "adb devices -l";
          }
          {
            category = "android";
            name     = "logcat";
            help     = "Filtered logcat for this app (extra flags after --)";
            command  = ''
              PID=$(adb shell pidof org.michael.plantapp 2>/dev/null)
              if [ -z "$PID" ]; then
                echo "⚠  App not running — showing unfiltered logcat"
                adb logcat "$@"
              else
                adb logcat --pid="$PID" "$@"
              fi
            '';
          }

          # ── Test ─────────────────────────────────────────────────────
          {
            category = "test";
            name     = "test-common";
            help     = "Run shared module checks";
            command  = "./gradlew :composeApp:check";
          }

          # ── Utilities ────────────────────────────────────────────────
          {
            category = "util";
            name     = "setup-sdk";
            help     = "Write local.properties with the Nix Android SDK path";
            command  = ''
              echo "## Auto-generated by nix devshell — do not edit manually" > local.properties
              echo "sdk.dir=$ANDROID_HOME" >> local.properties
              echo "✅ local.properties → sdk.dir=$ANDROID_HOME"
            '';
          }
          {
            category = "util";
            name     = "check-env";
            help     = "Verify that the development environment is healthy";
            command  = ''
              echo "── Environment ──"
              echo "  ANDROID_HOME     = $ANDROID_HOME"
              echo "  ANDROID_AVD_HOME = $ANDROID_AVD_HOME"
              echo "  JAVA_HOME        = $JAVA_HOME"
              echo ""
              echo "── SDK contents ──"
              if [ -d "$ANDROID_HOME/platforms" ]; then
                echo "  ✅ Platforms:    $(ls "$ANDROID_HOME/platforms/" 2>/dev/null | tr '\n' ' ')"
              else
                echo "  ❌ Platforms directory not found at \$ANDROID_HOME/platforms"
              fi
              if [ -d "$ANDROID_HOME/build-tools" ]; then
                echo "  ✅ Build tools:  $(ls "$ANDROID_HOME/build-tools/" 2>/dev/null | tr '\n' ' ')"
              else
                echo "  ❌ Build tools directory not found"
              fi
              if [ -d "$ANDROID_HOME/system-images" ]; then
                echo "  ✅ System images: present"
              else
                echo "  ❌ System images not found"
              fi
              echo ""
              echo "── Tools ──"
              command -v adb        &>/dev/null && echo "  ✅ adb:        $(adb --version 2>&1 | head -1)" || echo "  ❌ adb not found on PATH"
              command -v avdmanager &>/dev/null && echo "  ✅ avdmanager: found" || echo "  ❌ avdmanager not found on PATH"
              command -v emulator   &>/dev/null && echo "  ✅ emulator:   found" || echo "  ❌ emulator not found on PATH"
              echo ""
              echo "── Java ──"
              java -version 2>&1 | head -3
              echo ""
              echo "── KVM (hardware acceleration) ──"
              if [ -w /dev/kvm ]; then
                echo "  ✅ /dev/kvm is writable — emulator will use hardware acceleration"
              else
                echo "  ⚠  /dev/kvm not writable — emulator will be very slow"
                echo "     Fix: add your user to the 'kvm' group in your NixOS config"
              fi
            '';
          }
          {
            category = "util";
            name     = "clean";
            help     = "Clean all Gradle build artifacts";
            command  = "./gradlew clean";
          }
        ];
      };
    };
}
